name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 0.20.1
homepage: https://github.com/luanpotter/audioplayers

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin
      web:
        pluginClass: AudioplayersPlugin
        fileName: web/audioplayers_web.dart

dependencies:
  uuid:
  path_provider:
  http:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics:
  dartdoc:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"
